apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-web

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-web

  template:
    metadata:
      labels:
        app: simple-web

    spec:
      containers:
        - name: simple-web
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80